### PR TITLE
add uris

### PR DESCRIPTION
**Pull request by AlliedToasters**

### CODE REVIEW

**Comment by wgmi-rambo** [comment]
What does `METADATA_REVEAL_SECRET` do?

**Comment by wgmi-rambo** [comment]
Also, we don't have access to the wgm-takeover domain?

**Comment by AlliedToasters** [comment]
The secret is supposed to prevent people from viewing the metadata pre-reveal so they won't try to mint rares. Good point on the domain, let me find out!

**Comment by wgmi-rambo** [comment]
Not totally sure of your strategy with `METADATA_REVEAL_SECRET`.

From what I could see in `INITIAL_BASE_URI = f"https://unrgblmd-4vb3u.ondigitalocean.app/{METADATA_REVEAL_SECRET}?id="`, once a single nft is minted, the `METADATA_REVEAL_SECRET` will be revealed, and people can just enumerate on the ids.

**Comment by wgmi-rambo** [comment]
This repo might be of use to you:
[https://github.com/wgmi-rambo/nft-api-template](https://github.com/wgmi-rambo/nft-api-template)

**Comment by AlliedToasters** [comment]
We don't have access to the domain at the moment and it looks like things are in limbo. I just bought unruggables.io

**Comment by AlliedToasters** [comment]
`_initBaseURI` should not be visible until reveal

**Comment by wgmi-rambo** [comment]
Ah, true

**Pull request merged**
